// Code generated by goctl. DO NOT EDIT.
// Source: hello.proto

package server

import (
	"context"

	"12zrpc/internal/logic"
	"12zrpc/internal/svc"
	"12zrpc/pb"
)

type GreeterServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedGreeterServer
}

func NewGreeterServer(svcCtx *svc.ServiceContext) *GreeterServer {
	return &GreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *GreeterServer) SayHello(ctx context.Context, in *__.HelloRequest) (*__.HelloReply, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
