// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id string `path:"id"`
}

type OrderReplay struct {
	Id     string  `json:"id"`
	Name   string  `json:"name"`
	Amount float64 `json:"amount"`
}
