// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shorturlFieldNames          = builder.RawFieldNames(&Shorturl{})
	shorturlRows                = strings.Join(shorturlFieldNames, ",")
	shorturlRowsExpectAutoSet   = strings.Join(stringx.Remove(shorturlFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shorturlRowsWithPlaceHolder = strings.Join(stringx.Remove(shorturlFieldNames, "`short_link`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheShorturlShortLinkPrefix = "cache:1shorturl:shortLink:"
)

type (
	shorturlModel interface {
		Insert(ctx context.Context, data *Shorturl) (sql.Result, error)
		FindOne(ctx context.Context, shortLink string) (*Shorturl, error)
		Update(ctx context.Context, data *Shorturl) error
		Delete(ctx context.Context, shortLink string) error
	}

	defaultShorturlModel struct {
		sqlc.CachedConn
		table string
	}

	Shorturl struct {
		ShortLink string `db:"short_link"` // 短连接
		RealUrl   string `db:"real_url"`   // 真实连接
	}
)

func newShorturlModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultShorturlModel {
	return &defaultShorturlModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`1shorturl`",
	}
}

func (m *defaultShorturlModel) Delete(ctx context.Context, shortLink string) error {
	shorturlShortLinkKey := fmt.Sprintf("%s%v", cacheShorturlShortLinkPrefix, shortLink)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `short_link` = ?", m.table)
		return conn.ExecCtx(ctx, query, shortLink)
	}, shorturlShortLinkKey)
	return err
}

func (m *defaultShorturlModel) FindOne(ctx context.Context, shortLink string) (*Shorturl, error) {
	shorturlShortLinkKey := fmt.Sprintf("%s%v", cacheShorturlShortLinkPrefix, shortLink)
	var resp Shorturl
	err := m.QueryRowCtx(ctx, &resp, shorturlShortLinkKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `short_link` = ? limit 1", shorturlRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, shortLink)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShorturlModel) Insert(ctx context.Context, data *Shorturl) (sql.Result, error) {
	shorturlShortLinkKey := fmt.Sprintf("%s%v", cacheShorturlShortLinkPrefix, data.ShortLink)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, shorturlRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ShortLink, data.RealUrl)
	}, shorturlShortLinkKey)
	return ret, err
}

func (m *defaultShorturlModel) Update(ctx context.Context, data *Shorturl) error {
	shorturlShortLinkKey := fmt.Sprintf("%s%v", cacheShorturlShortLinkPrefix, data.ShortLink)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `short_link` = ?", m.table, shorturlRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.RealUrl, data.ShortLink)
	}, shorturlShortLinkKey)
	return err
}

func (m *defaultShorturlModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheShorturlShortLinkPrefix, primary)
}

func (m *defaultShorturlModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `short_link` = ? limit 1", shorturlRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShorturlModel) tableName() string {
	return m.table
}
