// Code generated by goctl. DO NOT EDIT.
// Source: transform.proto

package server

import (
	"context"

	"shorturl/rpc/transform/internal/logic"
	"shorturl/rpc/transform/internal/svc"
	"shorturl/rpc/transform/types/transform"
)

type TransformServer struct {
	svcCtx *svc.ServiceContext
	transform.UnimplementedTransformServer
}

func NewTransformServer(svcCtx *svc.ServiceContext) *TransformServer {
	return &TransformServer{
		svcCtx: svcCtx,
	}
}

// 根据真实的url返回短连接
func (s *TransformServer) GetShortLinkByRealUrl(ctx context.Context, in *transform.RealUrlToShortLinkReq) (*transform.RealUrlToShortLinkResp, error) {
	l := logic.NewGetShortLinkByRealUrlLogic(ctx, s.svcCtx)
	return l.GetShortLinkByRealUrl(in)
}

// 根据短连接返回真实的url
func (s *TransformServer) GetRealUrlByShortLink(ctx context.Context, in *transform.ShortLinkToRealUrlReq) (*transform.ShortLinkToRealUrlResp, error) {
	l := logic.NewGetRealUrlByShortLinkLogic(ctx, s.svcCtx)
	return l.GetRealUrlByShortLink(in)
}
