// Code generated by goctl. DO NOT EDIT.
// Source: hello.proto

package greeter

import (
	"context"

	"12zrpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HelloReply   = __.HelloReply
	HelloRequest = __.HelloRequest

	Greeter interface {
		SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	}

	defaultGreeter struct {
		cli zrpc.Client
	}
)

func NewGreeter(cli zrpc.Client) Greeter {
	return &defaultGreeter{
		cli: cli,
	}
}

func (m *defaultGreeter) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	client := __.NewGreeterClient(m.cli.Conn())
	return client.SayHello(ctx, in, opts...)
}
